sudo: true
language: node_js
node_js:
  - stable
script: 
  - npm test
install:
  - npm install
env:
  global:
  - secure: o5wwPppUisPgwkpgZ7Qxmto98uQgbpFFhN/JutX4SDv7L5yLhBEdErjujin2TSX4vuGVf0nkgsEvo7APQbvMrx2NEh539lBHL25pJoaylxUS7o757wW3ez5EYVnbYY4GrJI8nir2LTCR99wcGo/nJdF64ba78jVmcJo3ltTIGgZrZ5/nE3IywMvuuF3jo/hg2nuguBFMBOStRsDa/Wh665gx7wfovXMPKGgxpFFPU+U1fERgvvxtANDsxXpF30ZohnGGflgq/BTvojPM61nrZUTpigrI3AeC1x7Ozc3vls+7K35nw/6U4+UpsvvxBcSyB8xO0ixqKO3OtGh9xNX9w5Dr0xtpSrTOsx+hnzSv1TCypuTsE8Ff2ugGrEaae3ms6/z8EMQjfbIiPyM9ixx2TV+ynjIcYwqiWN34aVwx50Vi7JBs4H3hGMd+OFPB4xg3I27bFBopqvCBuOoQjHRJxKuUVJ5zX3SIMGpMlaRerUXRV695utYVGJW79PYamaihAPkczaXDK0/LkjQnASfeyfx1Ln/FOtItIcr6+4PBpZ4OJKKUGfHhuZQVrfo75TPBBG2Ln0kbcqHeSsKa4l3b+31yBYdozVY+DHG2vDfJHN9lvPMUyos/DFu/NI5wM/ZaB5vTTptBedT6LJrldk/twx8eT1Uv9IzioSVnXdnWmgw=
  - secure: J74FULcRT5+MXgFoLvHf6LVXHUgX47YwpEEnyxm1Wrn9Hj/1OHt1fwTJX5RHcbAC69OznAt0paSsANG32T/wStwH7nTTop9H/iOJEubyekkfqMCoHrrBbRUgj97x2tvYuvhIO2WwNoPeU2/lP8AgCh2BUmphuFnB1Mu2E0+RTchGewm2xwxX0NQhuZLiWEv0DR2sEeVP5L2+OW4LkBdKZgFr1RPtxi8lli9PgpKlVAdDpNxftYTOiWLJ9UCp5wBODL+Ptsh8gEBI2R4XrX/fXH/bzX84r4U9xZEurcDRM797lU4HQIBvr2bl6w55uDaxnuIjwYI2PKRqREcHV0YflRe0ArGwcH0y0eakv1ZR7PJ9tA07JsSjLlcR3pPkBh+85NKB4hCOk+J0GkVcUu0ZOOnb3PsTjE35+sM0ImPPPWBbX2W7ITy8xiVL2biw6DE3IOH+YrIsEeWiJXhM5mudANe6j1D7aqBKsScM/Ys2u/It8sQFi5wqj1AD/B0oiIC/xmvO7txVYymXW9UDcgEcrMglYjcOmzhrXBj/m1P88ifOgOlEDtWKYE/24p/ob0MEXOaBUI8ygauKlk+MvLhrpLeHSUsRTusFAyMaO+Cu2+EeHHoDgsVXUtTrg63hM08uV4VjESowFCk3/j7oPGS2xNlrxlGhgcW8pQ4w3FbfYfk=
